# Generated by Django 4.1.6 on 2023-03-11 09:58

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=thumbnails.fields.ImageField(upload_to='uploads/thumbnail'),
        ),
    ]
